[theme]
primaryColor = "#A067C1"       # Màu chính (tím)
backgroundColor = "#FFFFFF"    # Màu nền
secondaryBackgroundColor = "#F0F2F6"  # Màu nền phụ (sidebar)
textColor = "#31333F"          # Màu chữ

